title: Himanshu Shekhar
email: hshekhar0@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Data Science blog
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hshekhar.in" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Himanshu Shekhar # add your name
author-pic: pic.jpeg
about-author:

# Contact links
email: hshekhar0@gmail.com # Add your Email address
phone: # Add your Phone number
website: hshekhar.in # Add your website, do not add http://
linkedin: shekhartz # Add your Linkedin handle
github:  h-shekhar # Add your Github handle
twitter:  shekhartz # Add your Twitter handle
facebook: shekhartz # Add your Facebook handle
instagram: shekhartz # Add your Instagram handle
pinterest: # Add your Pinterest handle
medium: '@shekhartz'

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: hshekhar # Add your discus identifier

# Tracker
analytics: "UA-133548690-1" # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
